// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2_2yjuOOmg9SJ8masVT_IW0atX3afnyc',
    appId: '1:579024944563:web:6589fac80a10d112055fc6',
    messagingSenderId: '579024944563',
    projectId: 'notes-ecf2e',
    authDomain: 'notes-ecf2e.firebaseapp.com',
    databaseURL: 'https://notes-ecf2e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-ecf2e.appspot.com',
    measurementId: 'G-NMRCYYLR6K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO9n5WqWubL_nnWxCEctPKZV6_ALff7as',
    appId: '1:579024944563:android:6fce2bc684c68edf055fc6',
    messagingSenderId: '579024944563',
    projectId: 'notes-ecf2e',
    databaseURL: 'https://notes-ecf2e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-ecf2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKt28x43hO_vmYW5qWK_PnebJ3IRIDyGk',
    appId: '1:579024944563:ios:a7a3cfb218c0015e055fc6',
    messagingSenderId: '579024944563',
    projectId: 'notes-ecf2e',
    databaseURL: 'https://notes-ecf2e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-ecf2e.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKt28x43hO_vmYW5qWK_PnebJ3IRIDyGk',
    appId: '1:579024944563:ios:a7a3cfb218c0015e055fc6',
    messagingSenderId: '579024944563',
    projectId: 'notes-ecf2e',
    databaseURL: 'https://notes-ecf2e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-ecf2e.appspot.com',
    iosBundleId: 'com.example.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2_2yjuOOmg9SJ8masVT_IW0atX3afnyc',
    appId: '1:579024944563:web:0a07b1a0cc50398c055fc6',
    messagingSenderId: '579024944563',
    projectId: 'notes-ecf2e',
    authDomain: 'notes-ecf2e.firebaseapp.com',
    databaseURL: 'https://notes-ecf2e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'notes-ecf2e.appspot.com',
    measurementId: 'G-DBWSHJFSEK',
  );
}
